// ============================================================
// 전함 테이블 portraitImageAssetKey → Metro 정적 require
// 번호만 다른 수송선단·적함·AI 전함은 01(또는 가장 낮은 번호) 초상을 공유한다.
// 감사: npm run audit:npc-capital-ship-portraits
// 이어하기 프리페치는 기존 2장만. 나머지 초상은 조선소·구매창에서 온디맨드.
// ============================================================

import type { ImageSourcePropType } from 'react-native';

const PORTRAIT_BY_ASSET_KEY: Record<string, ImageSourcePropType> = {
  'assets/images/ship/Player_apex_legend_mk1.png': require('../../assets/images/ship/Player_apex_legend_mk1.png'),
  'assets/images/ship/Player_battlecruiser_apex.png': require('../../assets/images/ship/Player_battlecruiser_apex.png'),
  'assets/images/ship/Player_battlecruiser_mk1.png': require('../../assets/images/ship/Player_battlecruiser_mk1.png'),
  'assets/images/ship/Player_cruiser_mk1.png': require('../../assets/images/ship/Player_cruiser_mk1.png'),
  'assets/images/ship/Player_cruiser_mk2.png': require('../../assets/images/ship/Player_cruiser_mk2.png'),
  'assets/images/ship/Player_destroyer_mk1.png': require('../../assets/images/ship/Player_destroyer_mk1.png'),
  'assets/images/ship/Player_destroyer_mk2.png': require('../../assets/images/ship/Player_destroyer_mk2.png'),
  'assets/images/ship/Player_dreadnought_mk1.png': require('../../assets/images/ship/Player_dreadnought_mk1.png'),
  'assets/images/ship/Player_frigate_mk2.png': require('../../assets/images/ship/Player_frigate_mk2.png'),
  'assets/images/ship/Player_hunter_mk1.png': require('../../assets/images/ship/Player_hunter_mk1.png'),
  'assets/images/ship/Player_hunter_mk2.png': require('../../assets/images/ship/Player_hunter_mk2.png'),
  'assets/images/ship/Player_phantom_apex_legend_mk1.png': require('../../assets/images/ship/Player_phantom_apex_legend_mk1.png'),
  'assets/images/ship/Player_phantom_dreadnought_mk1.png': require('../../assets/images/ship/Player_phantom_dreadnought_mk1.png'),
  'assets/images/ship/Player_phantom_super_capital_mk1.png': require('../../assets/images/ship/Player_phantom_super_capital_mk1.png'),
  'assets/images/ship/Player_raptor_bc_apex.png': require('../../assets/images/ship/Player_raptor_bc_apex.png'),
  'assets/images/ship/Player_raptor_bc_mk1.png': require('../../assets/images/ship/Player_raptor_bc_mk1.png'),
  'assets/images/ship/Player_scout_ship.png': require('../../assets/images/ship/Player_scout_ship.png'),
  'assets/images/ship/Player_shadow_cruiser_mk1.png': require('../../assets/images/ship/Player_shadow_cruiser_mk1.png'),
  'assets/images/ship/Player_shadow_cruiser_mk2.png': require('../../assets/images/ship/Player_shadow_cruiser_mk2.png'),
  'assets/images/ship/Player_super_capital_mk1.png': require('../../assets/images/ship/Player_super_capital_mk1.png'),
  'assets/images/ship/npc_ai_clan_neutral_flagship.png': require('../../assets/images/ship/npc_ai_clan_neutral_flagship.png'),
  'assets/images/ship/npc_ai_clan_pvp_flagship.png': require('../../assets/images/ship/npc_ai_clan_pvp_flagship.png'),
  'assets/images/ship/npc_ai_clan_safe_flagship.png': require('../../assets/images/ship/npc_ai_clan_safe_flagship.png'),
  'assets/images/ship/npc_arc_presence_ship_01.png': require('../../assets/images/ship/npc_arc_presence_ship_01.png'),
  'assets/images/ship/npc_arc_presence_ship_02.png': require('../../assets/images/ship/npc_arc_presence_ship_02.png'),
  'assets/images/ship/npc_arc_presence_ship_03.png': require('../../assets/images/ship/npc_arc_presence_ship_03.png'),
  'assets/images/ship/npc_arc_presence_ship_04.png': require('../../assets/images/ship/npc_arc_presence_ship_04.png'),
  'assets/images/ship/npc_arc_presence_ship_05.png': require('../../assets/images/ship/npc_arc_presence_ship_05.png'),
  'assets/images/ship/npc_arc_presence_ship_06.png': require('../../assets/images/ship/npc_arc_presence_ship_06.png'),
  'assets/images/ship/npc_arc_presence_ship_07.png': require('../../assets/images/ship/npc_arc_presence_ship_07.png'),
  'assets/images/ship/npc_arc_presence_ship_08.png': require('../../assets/images/ship/npc_arc_presence_ship_08.png'),
  'assets/images/ship/npc_arc_presence_ship_09.png': require('../../assets/images/ship/npc_arc_presence_ship_09.png'),
  'assets/images/ship/npc_arc_presence_ship_10.png': require('../../assets/images/ship/npc_arc_presence_ship_10.png'),
  'assets/images/ship/npc_arc_presence_ship_11.png': require('../../assets/images/ship/npc_arc_presence_ship_11.png'),
  'assets/images/ship/npc_arc_presence_ship_12.png': require('../../assets/images/ship/npc_arc_presence_ship_12.png'),
  'assets/images/ship/npc_arc_seed_ship_abyss.png': require('../../assets/images/ship/npc_arc_seed_ship_abyss.png'),
  'assets/images/ship/npc_arc_seed_ship_arcadia.png': require('../../assets/images/ship/npc_arc_seed_ship_arcadia.png'),
  'assets/images/ship/npc_arc_seed_ship_arcfire_core.png': require('../../assets/images/ship/npc_arc_seed_ship_arcfire_core.png'),
  'assets/images/ship/npc_arc_seed_ship_blood_field.png': require('../../assets/images/ship/npc_arc_seed_ship_blood_field.png'),
  'assets/images/ship/npc_arc_seed_ship_crimson_zone.png': require('../../assets/images/ship/npc_arc_seed_ship_crimson_zone.png'),
  'assets/images/ship/npc_arc_seed_ship_dark_rift.png': require('../../assets/images/ship/npc_arc_seed_ship_dark_rift.png'),
  'assets/images/ship/npc_arc_seed_ship_draco_nebula.png': require('../../assets/images/ship/npc_arc_seed_ship_draco_nebula.png'),
  'assets/images/ship/npc_arc_seed_ship_eternity.png': require('../../assets/images/ship/npc_arc_seed_ship_eternity.png'),
  'assets/images/ship/npc_arc_seed_ship_genesis.png': require('../../assets/images/ship/npc_arc_seed_ship_genesis.png'),
  'assets/images/ship/npc_arc_seed_ship_helios.png': require('../../assets/images/ship/npc_arc_seed_ship_helios.png'),
  'assets/images/ship/npc_arc_seed_ship_iron_cross.png': require('../../assets/images/ship/npc_arc_seed_ship_iron_cross.png'),
  'assets/images/ship/npc_arc_seed_ship_minerva.png': require('../../assets/images/ship/npc_arc_seed_ship_minerva.png'),
  'assets/images/ship/npc_arc_seed_ship_new_eden.png': require('../../assets/images/ship/npc_arc_seed_ship_new_eden.png'),
  'assets/images/ship/npc_arc_seed_ship_nightfall.png': require('../../assets/images/ship/npc_arc_seed_ship_nightfall.png'),
  'assets/images/ship/npc_arc_seed_ship_omega_station.png': require('../../assets/images/ship/npc_arc_seed_ship_omega_station.png'),
  'assets/images/ship/npc_arc_seed_ship_perseus.png': require('../../assets/images/ship/npc_arc_seed_ship_perseus.png'),
  'assets/images/ship/npc_arc_seed_ship_shadow_nexus.png': require('../../assets/images/ship/npc_arc_seed_ship_shadow_nexus.png'),
  'assets/images/ship/npc_arc_seed_ship_sirius.png': require('../../assets/images/ship/npc_arc_seed_ship_sirius.png'),
  'assets/images/ship/npc_arc_seed_ship_solar_port.png': require('../../assets/images/ship/npc_arc_seed_ship_solar_port.png'),
  'assets/images/ship/npc_arc_seed_ship_titan_gate.png': require('../../assets/images/ship/npc_arc_seed_ship_titan_gate.png'),
  'assets/images/ship/npc_arc_seed_ship_vega_outpost.png': require('../../assets/images/ship/npc_arc_seed_ship_vega_outpost.png'),
  'assets/images/ship/npc_arcadia_orbit_1.png': require('../../assets/images/ship/npc_arcadia_orbit_1.png'),
  'assets/images/ship/npc_blue_fleet_1.png': require('../../assets/images/ship/npc_blue_fleet_1.png'),
  'assets/images/ship/npc_draco_escort_01.png': require('../../assets/images/ship/npc_draco_escort_01.png'),
  'assets/images/ship/npc_draco_patrol_01.png': require('../../assets/images/ship/npc_draco_patrol_01.png'),
  'assets/images/ship/npc_eden_orbit_4.png': require('../../assets/images/ship/npc_eden_orbit_4.png'),
  'assets/images/ship/npc_enemy_abyss_01.png': require('../../assets/images/ship/npc_enemy_abyss_01.png'),
  'assets/images/ship/npc_enemy_arcadia_01.png': require('../../assets/images/ship/npc_enemy_arcadia_01.png'),
  'assets/images/ship/npc_enemy_blood_01.png': require('../../assets/images/ship/npc_enemy_blood_01.png'),
  'assets/images/ship/npc_enemy_core_01.png': require('../../assets/images/ship/npc_enemy_core_01.png'),
  'assets/images/ship/npc_enemy_crimson_01.png': require('../../assets/images/ship/npc_enemy_crimson_01.png'),
  'assets/images/ship/npc_enemy_dark_01.png': require('../../assets/images/ship/npc_enemy_dark_01.png'),
  'assets/images/ship/npc_enemy_draco_01.png': require('../../assets/images/ship/npc_enemy_draco_01.png'),
  'assets/images/ship/npc_enemy_eden_01.png': require('../../assets/images/ship/npc_enemy_eden_01.png'),
  'assets/images/ship/npc_enemy_eternity_01.png': require('../../assets/images/ship/npc_enemy_eternity_01.png'),
  'assets/images/ship/npc_enemy_helios_01.png': require('../../assets/images/ship/npc_enemy_helios_01.png'),
  'assets/images/ship/npc_enemy_iron_01.png': require('../../assets/images/ship/npc_enemy_iron_01.png'),
  'assets/images/ship/npc_enemy_minerva_01.png': require('../../assets/images/ship/npc_enemy_minerva_01.png'),
  'assets/images/ship/npc_enemy_nightfall_01.png': require('../../assets/images/ship/npc_enemy_nightfall_01.png'),
  'assets/images/ship/npc_enemy_omega_01.png': require('../../assets/images/ship/npc_enemy_omega_01.png'),
  'assets/images/ship/npc_enemy_perseus_01.png': require('../../assets/images/ship/npc_enemy_perseus_01.png'),
  'assets/images/ship/npc_enemy_shadow_01.png': require('../../assets/images/ship/npc_enemy_shadow_01.png'),
  'assets/images/ship/npc_enemy_sirius_01.png': require('../../assets/images/ship/npc_enemy_sirius_01.png'),
  'assets/images/ship/npc_enemy_solar_01.png': require('../../assets/images/ship/npc_enemy_solar_01.png'),
  'assets/images/ship/npc_enemy_titan_01.png': require('../../assets/images/ship/npc_enemy_titan_01.png'),
  'assets/images/ship/npc_enemy_vega_01.png': require('../../assets/images/ship/npc_enemy_vega_01.png'),
  'assets/images/ship/npc_faction_cargo_ship_e_01.png': require('../../assets/images/ship/npc_faction_cargo_ship_e_01.png'),
  'assets/images/ship/npc_faction_cargo_ship_n_01.png': require('../../assets/images/ship/npc_faction_cargo_ship_n_01.png'),
  'assets/images/ship/npc_faction_cargo_ship_s_01.png': require('../../assets/images/ship/npc_faction_cargo_ship_s_01.png'),
  'assets/images/ship/npc_faction_cargo_ship_w_01.png': require('../../assets/images/ship/npc_faction_cargo_ship_w_01.png'),
  'assets/images/ship/npc_gov_genesis_flagship.png': require('../../assets/images/ship/npc_gov_genesis_flagship.png'),
  'assets/images/ship/npc_gov_helios_flagship.png': require('../../assets/images/ship/npc_gov_helios_flagship.png'),
  'assets/images/ship/npc_gov_iron_flagship.png': require('../../assets/images/ship/npc_gov_iron_flagship.png'),
  'assets/images/ship/npc_gov_minerva_flagship.png': require('../../assets/images/ship/npc_gov_minerva_flagship.png'),
  'assets/images/ship/npc_mock_ai_ship_01.png': require('../../assets/images/ship/npc_mock_ai_ship_01.png'),
  'assets/images/ship/npc_neweden_blue_7.png': require('../../assets/images/ship/npc_neweden_blue_7.png'),
  'assets/images/ship/npc_neweden_red_7.png': require('../../assets/images/ship/npc_neweden_red_7.png'),
  'assets/images/ship/npc_red_fleet_1.png': require('../../assets/images/ship/npc_red_fleet_1.png'),
  'assets/images/ship/npc_red_fleet_3.png': require('../../assets/images/ship/npc_red_fleet_3.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_01.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_01.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_02.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_02.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_03.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_03.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_04.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_04.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_05.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_05.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_06.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_06.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_07.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_07.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_08.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_08.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_09.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_09.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_10.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_10.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_11.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_11.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_12.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_12.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_13.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_13.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_14.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_14.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_15.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_15.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_16.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_16.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_17.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_17.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_18.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_18.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_19.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_19.png'),
  'assets/images/ship/npc_ship_gov_reserve_blue_20.png': require('../../assets/images/ship/npc_ship_gov_reserve_blue_20.png'),
  'assets/images/ship/npc_ship_gov_reserve_neutral_01.png': require('../../assets/images/ship/npc_ship_gov_reserve_neutral_01.png'),
  'assets/images/ship/npc_ship_gov_reserve_neutral_02.png': require('../../assets/images/ship/npc_ship_gov_reserve_neutral_02.png'),
  'assets/images/ship/npc_ship_gov_reserve_neutral_03.png': require('../../assets/images/ship/npc_ship_gov_reserve_neutral_03.png'),
  'assets/images/ship/npc_ship_gov_reserve_neutral_04.png': require('../../assets/images/ship/npc_ship_gov_reserve_neutral_04.png'),
  'assets/images/ship/npc_ship_gov_reserve_neutral_05.png': require('../../assets/images/ship/npc_ship_gov_reserve_neutral_05.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_01.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_01.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_02.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_02.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_03.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_03.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_04.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_04.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_05.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_05.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_06.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_06.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_07.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_07.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_08.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_08.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_09.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_09.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_10.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_10.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_11.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_11.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_12.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_12.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_13.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_13.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_14.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_14.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_15.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_15.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_16.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_16.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_17.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_17.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_18.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_18.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_19.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_19.png'),
  'assets/images/ship/npc_ship_gov_reserve_red_20.png': require('../../assets/images/ship/npc_ship_gov_reserve_red_20.png'),
  'assets/images/ship/npc_solar_guard_1.png': require('../../assets/images/ship/npc_solar_guard_1.png'),
  'assets/images/ship/npc_test_ship_001.png': require('../../assets/images/ship/npc_test_ship_001.png'),
  'assets/images/ship/npc_vega_blue_7.png': require('../../assets/images/ship/npc_vega_blue_7.png'),
  'assets/images/ship/npc_vega_guard_1.png': require('../../assets/images/ship/npc_vega_guard_1.png'),
  'assets/images/ship/npc_vega_red_4.png': require('../../assets/images/ship/npc_vega_red_4.png'),
  'assets/images/ship/npc_vega_red_5.png': require('../../assets/images/ship/npc_vega_red_5.png'),
  'assets/images/ship/npc_vega_test_ship_a.png': require('../../assets/images/ship/npc_vega_test_ship_a.png'),
  'assets/images/ship/npc_vega_test_ship_b.png': require('../../assets/images/ship/npc_vega_test_ship_b.png'),
  'assets/images/ship/npc_wave_invader_t1.png': require('../../assets/images/ship/npc_wave_invader_t1.png'),
  'assets/images/ship/player_wave_ship.png': require('../../assets/images/ship/player_wave_ship.png'),
  'assets/images/ship/npc_enemy_arcadia_02.png': require('../../assets/images/ship/npc_enemy_arcadia_02.png'),
  'assets/images/ship/npc_enemy_draco_02.png': require('../../assets/images/ship/npc_enemy_draco_02.png'),
  'assets/images/ship/npc_enemy_omega_02.png': require('../../assets/images/ship/npc_enemy_omega_02.png'),
  'assets/images/ship/npc_enemy_sirius_02.png': require('../../assets/images/ship/npc_enemy_sirius_02.png'),
  'assets/images/ship/npc_enemy_perseus_02.png': require('../../assets/images/ship/npc_enemy_perseus_02.png'),
  'assets/images/ship/npc_enemy_crimson_02.png': require('../../assets/images/ship/npc_enemy_crimson_02.png'),
  'assets/images/ship/npc_enemy_dark_02.png': require('../../assets/images/ship/npc_enemy_dark_02.png'),
  'assets/images/ship/npc_enemy_nightfall_02.png': require('../../assets/images/ship/npc_enemy_nightfall_02.png'),
  'assets/images/ship/ship_001.png': require('../../assets/images/ship/ship_001.png'),
};

const CRITICAL_PREFETCH_KEYS = [
  'assets/images/ship/ship_001.png',
  'assets/images/ship/npc_test_ship_001.png',
] as const;

export function resolveNpcCapitalShipPortraitSource(
  key: string | undefined | null,
): ImageSourcePropType | null {
  if (key == null) return null;
  const k = String(key).trim();
  if (!k) return null;
  return PORTRAIT_BY_ASSET_KEY[k] ?? null;
}

/** 이어하기 로딩에서 디코드할 전함 초상. 카탈로그 전수는 넣지 않는다. */
export function listNpcCapitalPortraitSources(): ImageSourcePropType[] {
  const out: ImageSourcePropType[] = [];
  for (let i = 0; i < CRITICAL_PREFETCH_KEYS.length; i += 1) {
    const src = PORTRAIT_BY_ASSET_KEY[CRITICAL_PREFETCH_KEYS[i]];
    if (src) out.push(src);
  }
  return out;
}
