import { Image, type ImageSourcePropType } from 'react-native';

/**
 * CSV `portraitImageAssetKey` → Metro 정적 require.
 * 새 PNG: assets/images/npc/ 저장 후 `npm run` ingest 또는 본 스크립트 재실행.
 * 픽셀 규격: npcPortraitPixelContract.ts (240×240).
 * 금지: listCriticalSessionImageSources 에 함장 초상 전수 편입.
 */
const NPC_CAPTAIN_PORTRAIT_BY_ASSET_KEY: Record<string, ImageSourcePropType> = {
  'assets/images/npc/stella_aris_char001.png': require('../../assets/images/npc/stella_aris_char001.png'),
  'assets/images/npc/mia_bello_char002.png': require('../../assets/images/npc/mia_bello_char002.png'),
  'assets/images/npc/noname_char003.png': require('../../assets/images/npc/noname_char003.png'),
  'assets/images/npc/noname_char004.png': require('../../assets/images/npc/noname_char004.png'),
  'assets/images/npc/noname_char005.png': require('../../assets/images/npc/noname_char005.png'),
  'assets/images/npc/noname_char006.png': require('../../assets/images/npc/noname_char006.png'),
  'assets/images/npc/noname_char007.png': require('../../assets/images/npc/noname_char007.png'),
  'assets/images/npc/noname_char008.png': require('../../assets/images/npc/noname_char008.png'),
  'assets/images/npc/noname_char009.png': require('../../assets/images/npc/noname_char009.png'),
  'assets/images/npc/noname_char010.png': require('../../assets/images/npc/noname_char010.png'),
  /** story_scene_pages 레거시 키 — npc/ 하위와 동일 에셋 */
  'assets/images/stella_aris_char001.png': require('../../assets/images/npc/stella_aris_char001.png'),
  /** 테이블 고유 정본 */
  'assets/images/npc/Player_pilot.png': require('../../assets/images/npc/Player_pilot.png'),
  'assets/images/npc/npc_cpt_ai_clan_neutral_01.png': require('../../assets/images/npc/npc_cpt_ai_clan_neutral_01.png'),
  'assets/images/npc/npc_cpt_ai_clan_pvp_01.png': require('../../assets/images/npc/npc_cpt_ai_clan_pvp_01.png'),
  'assets/images/npc/npc_cpt_ai_clan_safe_01.png': require('../../assets/images/npc/npc_cpt_ai_clan_safe_01.png'),
  'assets/images/npc/npc_cpt_ai_robot_default.png': require('../../assets/images/npc/npc_cpt_ai_robot_default.png'),
  'assets/images/npc/npc_cpt_anomaly_researcher.png': require('../../assets/images/npc/npc_cpt_anomaly_researcher.png'),
  'assets/images/npc/npc_cpt_arc_pf_01.png': require('../../assets/images/npc/npc_cpt_arc_pf_01.png'),
  'assets/images/npc/npc_cpt_arc_pf_02.png': require('../../assets/images/npc/npc_cpt_arc_pf_02.png'),
  'assets/images/npc/npc_cpt_arc_pf_03.png': require('../../assets/images/npc/npc_cpt_arc_pf_03.png'),
  'assets/images/npc/npc_cpt_arc_pf_04.png': require('../../assets/images/npc/npc_cpt_arc_pf_04.png'),
  'assets/images/npc/npc_cpt_arc_pf_05.png': require('../../assets/images/npc/npc_cpt_arc_pf_05.png'),
  'assets/images/npc/npc_cpt_arc_pf_06.png': require('../../assets/images/npc/npc_cpt_arc_pf_06.png'),
  'assets/images/npc/npc_cpt_arc_pf_07.png': require('../../assets/images/npc/npc_cpt_arc_pf_07.png'),
  'assets/images/npc/npc_cpt_arc_pf_08.png': require('../../assets/images/npc/npc_cpt_arc_pf_08.png'),
  'assets/images/npc/npc_cpt_arc_pf_09.png': require('../../assets/images/npc/npc_cpt_arc_pf_09.png'),
  'assets/images/npc/npc_cpt_arc_pf_10.png': require('../../assets/images/npc/npc_cpt_arc_pf_10.png'),
  'assets/images/npc/npc_cpt_arc_pf_11.png': require('../../assets/images/npc/npc_cpt_arc_pf_11.png'),
  'assets/images/npc/npc_cpt_arc_pf_12.png': require('../../assets/images/npc/npc_cpt_arc_pf_12.png'),
  'assets/images/npc/npc_cpt_arc_seed_abyss.png': require('../../assets/images/npc/npc_cpt_arc_seed_abyss.png'),
  'assets/images/npc/npc_cpt_arc_seed_arcadia.png': require('../../assets/images/npc/npc_cpt_arc_seed_arcadia.png'),
  'assets/images/npc/npc_cpt_arc_seed_arcfire_core.png': require('../../assets/images/npc/npc_cpt_arc_seed_arcfire_core.png'),
  'assets/images/npc/npc_cpt_arc_seed_blood_field.png': require('../../assets/images/npc/npc_cpt_arc_seed_blood_field.png'),
  'assets/images/npc/npc_cpt_arc_seed_crimson_zone.png': require('../../assets/images/npc/npc_cpt_arc_seed_crimson_zone.png'),
  'assets/images/npc/npc_cpt_arc_seed_dark_rift.png': require('../../assets/images/npc/npc_cpt_arc_seed_dark_rift.png'),
  'assets/images/npc/npc_cpt_arc_seed_draco_nebula.png': require('../../assets/images/npc/npc_cpt_arc_seed_draco_nebula.png'),
  'assets/images/npc/npc_cpt_arc_seed_eternity.png': require('../../assets/images/npc/npc_cpt_arc_seed_eternity.png'),
  'assets/images/npc/npc_cpt_arc_seed_genesis.png': require('../../assets/images/npc/npc_cpt_arc_seed_genesis.png'),
  'assets/images/npc/npc_cpt_arc_seed_helios.png': require('../../assets/images/npc/npc_cpt_arc_seed_helios.png'),
  'assets/images/npc/npc_cpt_arc_seed_iron_cross.png': require('../../assets/images/npc/npc_cpt_arc_seed_iron_cross.png'),
  'assets/images/npc/npc_cpt_arc_seed_minerva.png': require('../../assets/images/npc/npc_cpt_arc_seed_minerva.png'),
  'assets/images/npc/npc_cpt_arc_seed_new_eden.png': require('../../assets/images/npc/npc_cpt_arc_seed_new_eden.png'),
  'assets/images/npc/npc_cpt_arc_seed_nightfall.png': require('../../assets/images/npc/npc_cpt_arc_seed_nightfall.png'),
  'assets/images/npc/npc_cpt_arc_seed_omega_station.png': require('../../assets/images/npc/npc_cpt_arc_seed_omega_station.png'),
  'assets/images/npc/npc_cpt_arc_seed_perseus.png': require('../../assets/images/npc/npc_cpt_arc_seed_perseus.png'),
  'assets/images/npc/npc_cpt_arc_seed_shadow_nexus.png': require('../../assets/images/npc/npc_cpt_arc_seed_shadow_nexus.png'),
  'assets/images/npc/npc_cpt_arc_seed_sirius.png': require('../../assets/images/npc/npc_cpt_arc_seed_sirius.png'),
  'assets/images/npc/npc_cpt_arc_seed_solar_port.png': require('../../assets/images/npc/npc_cpt_arc_seed_solar_port.png'),
  'assets/images/npc/npc_cpt_arc_seed_titan_gate.png': require('../../assets/images/npc/npc_cpt_arc_seed_titan_gate.png'),
  'assets/images/npc/npc_cpt_arc_seed_vega_outpost.png': require('../../assets/images/npc/npc_cpt_arc_seed_vega_outpost.png'),
  'assets/images/npc/npc_cpt_arcadia_lane_01.png': require('../../assets/images/npc/npc_cpt_arcadia_lane_01.png'),
  'assets/images/npc/npc_cpt_arcadia_lane_02.png': require('../../assets/images/npc/npc_cpt_arcadia_lane_02.png'),
  'assets/images/npc/npc_cpt_bar_ret_01.png': require('../../assets/images/npc/npc_cpt_bar_ret_01.png'),
  'assets/images/npc/npc_cpt_bar_ret_02.png': require('../../assets/images/npc/npc_cpt_bar_ret_02.png'),
  'assets/images/npc/npc_cpt_bar_ret_03.png': require('../../assets/images/npc/npc_cpt_bar_ret_03.png'),
  'assets/images/npc/npc_cpt_bar_ret_04.png': require('../../assets/images/npc/npc_cpt_bar_ret_04.png'),
  'assets/images/npc/npc_cpt_bar_ret_05.png': require('../../assets/images/npc/npc_cpt_bar_ret_05.png'),
  'assets/images/npc/npc_cpt_bar_ret_06.png': require('../../assets/images/npc/npc_cpt_bar_ret_06.png'),
  'assets/images/npc/npc_cpt_bar_ret_07.png': require('../../assets/images/npc/npc_cpt_bar_ret_07.png'),
  'assets/images/npc/npc_cpt_bar_ret_08.png': require('../../assets/images/npc/npc_cpt_bar_ret_08.png'),
  'assets/images/npc/npc_cpt_bar_ret_09.png': require('../../assets/images/npc/npc_cpt_bar_ret_09.png'),
  'assets/images/npc/npc_cpt_bar_ret_10.png': require('../../assets/images/npc/npc_cpt_bar_ret_10.png'),
  'assets/images/npc/npc_cpt_bar_ret_11.png': require('../../assets/images/npc/npc_cpt_bar_ret_11.png'),
  'assets/images/npc/npc_cpt_bar_ret_12.png': require('../../assets/images/npc/npc_cpt_bar_ret_12.png'),
  'assets/images/npc/npc_cpt_bar_ret_13.png': require('../../assets/images/npc/npc_cpt_bar_ret_13.png'),
  'assets/images/npc/npc_cpt_bar_ret_14.png': require('../../assets/images/npc/npc_cpt_bar_ret_14.png'),
  'assets/images/npc/npc_cpt_bar_ret_15.png': require('../../assets/images/npc/npc_cpt_bar_ret_15.png'),
  'assets/images/npc/npc_cpt_bar_ret_16.png': require('../../assets/images/npc/npc_cpt_bar_ret_16.png'),
  'assets/images/npc/npc_cpt_bar_ret_17.png': require('../../assets/images/npc/npc_cpt_bar_ret_17.png'),
  'assets/images/npc/npc_cpt_bar_ret_18.png': require('../../assets/images/npc/npc_cpt_bar_ret_18.png'),
  'assets/images/npc/npc_cpt_draco_escort_01.png': require('../../assets/images/npc/npc_cpt_draco_escort_01.png'),
  'assets/images/npc/npc_cpt_draco_obs_01.png': require('../../assets/images/npc/npc_cpt_draco_obs_01.png'),
  'assets/images/npc/npc_cpt_eden_08.png': require('../../assets/images/npc/npc_cpt_eden_08.png'),
  'assets/images/npc/npc_cpt_eden_09.png': require('../../assets/images/npc/npc_cpt_eden_09.png'),
  'assets/images/npc/npc_cpt_eden_10.png': require('../../assets/images/npc/npc_cpt_eden_10.png'),
  'assets/images/npc/npc_cpt_enemy_abyss_01.png': require('../../assets/images/npc/npc_cpt_enemy_abyss_01.png'),
  'assets/images/npc/npc_cpt_enemy_abyss_02.png': require('../../assets/images/npc/npc_cpt_enemy_abyss_02.png'),
  'assets/images/npc/npc_cpt_enemy_abyss_03.png': require('../../assets/images/npc/npc_cpt_enemy_abyss_03.png'),
  'assets/images/npc/npc_cpt_enemy_arcadia_01.png': require('../../assets/images/npc/npc_cpt_enemy_arcadia_01.png'),
  'assets/images/npc/npc_cpt_enemy_arcadia_02.png': require('../../assets/images/npc/npc_cpt_enemy_arcadia_02.png'),
  'assets/images/npc/npc_cpt_enemy_arcadia_03.png': require('../../assets/images/npc/npc_cpt_enemy_arcadia_03.png'),
  'assets/images/npc/npc_cpt_enemy_blood_01.png': require('../../assets/images/npc/npc_cpt_enemy_blood_01.png'),
  'assets/images/npc/npc_cpt_enemy_blood_02.png': require('../../assets/images/npc/npc_cpt_enemy_blood_02.png'),
  'assets/images/npc/npc_cpt_enemy_blood_03.png': require('../../assets/images/npc/npc_cpt_enemy_blood_03.png'),
  'assets/images/npc/npc_cpt_enemy_core_01.png': require('../../assets/images/npc/npc_cpt_enemy_core_01.png'),
  'assets/images/npc/npc_cpt_enemy_core_02.png': require('../../assets/images/npc/npc_cpt_enemy_core_02.png'),
  'assets/images/npc/npc_cpt_enemy_core_03.png': require('../../assets/images/npc/npc_cpt_enemy_core_03.png'),
  'assets/images/npc/npc_cpt_enemy_crimson_01.png': require('../../assets/images/npc/npc_cpt_enemy_crimson_01.png'),
  'assets/images/npc/npc_cpt_enemy_crimson_02.png': require('../../assets/images/npc/npc_cpt_enemy_crimson_02.png'),
  'assets/images/npc/npc_cpt_enemy_crimson_03.png': require('../../assets/images/npc/npc_cpt_enemy_crimson_03.png'),
  'assets/images/npc/npc_cpt_enemy_dark_01.png': require('../../assets/images/npc/npc_cpt_enemy_dark_01.png'),
  'assets/images/npc/npc_cpt_enemy_dark_02.png': require('../../assets/images/npc/npc_cpt_enemy_dark_02.png'),
  'assets/images/npc/npc_cpt_enemy_dark_03.png': require('../../assets/images/npc/npc_cpt_enemy_dark_03.png'),
  'assets/images/npc/npc_cpt_enemy_draco_01.png': require('../../assets/images/npc/npc_cpt_enemy_draco_01.png'),
  'assets/images/npc/npc_cpt_enemy_draco_02.png': require('../../assets/images/npc/npc_cpt_enemy_draco_02.png'),
  'assets/images/npc/npc_cpt_enemy_draco_03.png': require('../../assets/images/npc/npc_cpt_enemy_draco_03.png'),
  'assets/images/npc/npc_cpt_enemy_eden_01.png': require('../../assets/images/npc/npc_cpt_enemy_eden_01.png'),
  'assets/images/npc/npc_cpt_enemy_eternity_01.png': require('../../assets/images/npc/npc_cpt_enemy_eternity_01.png'),
  'assets/images/npc/npc_cpt_enemy_eternity_02.png': require('../../assets/images/npc/npc_cpt_enemy_eternity_02.png'),
  'assets/images/npc/npc_cpt_enemy_eternity_03.png': require('../../assets/images/npc/npc_cpt_enemy_eternity_03.png'),
  'assets/images/npc/npc_cpt_enemy_helios_01.png': require('../../assets/images/npc/npc_cpt_enemy_helios_01.png'),
  'assets/images/npc/npc_cpt_enemy_helios_02.png': require('../../assets/images/npc/npc_cpt_enemy_helios_02.png'),
  'assets/images/npc/npc_cpt_enemy_helios_03.png': require('../../assets/images/npc/npc_cpt_enemy_helios_03.png'),
  'assets/images/npc/npc_cpt_enemy_iron_01.png': require('../../assets/images/npc/npc_cpt_enemy_iron_01.png'),
  'assets/images/npc/npc_cpt_enemy_iron_02.png': require('../../assets/images/npc/npc_cpt_enemy_iron_02.png'),
  'assets/images/npc/npc_cpt_enemy_iron_03.png': require('../../assets/images/npc/npc_cpt_enemy_iron_03.png'),
  'assets/images/npc/npc_cpt_enemy_minerva_01.png': require('../../assets/images/npc/npc_cpt_enemy_minerva_01.png'),
  'assets/images/npc/npc_cpt_enemy_nightfall_01.png': require('../../assets/images/npc/npc_cpt_enemy_nightfall_01.png'),
  'assets/images/npc/npc_cpt_enemy_nightfall_02.png': require('../../assets/images/npc/npc_cpt_enemy_nightfall_02.png'),
  'assets/images/npc/npc_cpt_enemy_nightfall_03.png': require('../../assets/images/npc/npc_cpt_enemy_nightfall_03.png'),
  'assets/images/npc/npc_cpt_enemy_omega_01.png': require('../../assets/images/npc/npc_cpt_enemy_omega_01.png'),
  'assets/images/npc/npc_cpt_enemy_omega_02.png': require('../../assets/images/npc/npc_cpt_enemy_omega_02.png'),
  'assets/images/npc/npc_cpt_enemy_omega_03.png': require('../../assets/images/npc/npc_cpt_enemy_omega_03.png'),
  'assets/images/npc/npc_cpt_enemy_perseus_01.png': require('../../assets/images/npc/npc_cpt_enemy_perseus_01.png'),
  'assets/images/npc/npc_cpt_enemy_perseus_02.png': require('../../assets/images/npc/npc_cpt_enemy_perseus_02.png'),
  'assets/images/npc/npc_cpt_enemy_perseus_03.png': require('../../assets/images/npc/npc_cpt_enemy_perseus_03.png'),
  'assets/images/npc/npc_cpt_enemy_shadow_01.png': require('../../assets/images/npc/npc_cpt_enemy_shadow_01.png'),
  'assets/images/npc/npc_cpt_enemy_shadow_02.png': require('../../assets/images/npc/npc_cpt_enemy_shadow_02.png'),
  'assets/images/npc/npc_cpt_enemy_shadow_03.png': require('../../assets/images/npc/npc_cpt_enemy_shadow_03.png'),
  'assets/images/npc/npc_cpt_enemy_sirius_01.png': require('../../assets/images/npc/npc_cpt_enemy_sirius_01.png'),
  'assets/images/npc/npc_cpt_enemy_sirius_02.png': require('../../assets/images/npc/npc_cpt_enemy_sirius_02.png'),
  'assets/images/npc/npc_cpt_enemy_sirius_03.png': require('../../assets/images/npc/npc_cpt_enemy_sirius_03.png'),
  'assets/images/npc/npc_cpt_enemy_solar_01.png': require('../../assets/images/npc/npc_cpt_enemy_solar_01.png'),
  'assets/images/npc/npc_cpt_enemy_titan_01.png': require('../../assets/images/npc/npc_cpt_enemy_titan_01.png'),
  'assets/images/npc/npc_cpt_enemy_titan_02.png': require('../../assets/images/npc/npc_cpt_enemy_titan_02.png'),
  'assets/images/npc/npc_cpt_enemy_titan_03.png': require('../../assets/images/npc/npc_cpt_enemy_titan_03.png'),
  'assets/images/npc/npc_cpt_enemy_vega_01.png': require('../../assets/images/npc/npc_cpt_enemy_vega_01.png'),
  'assets/images/npc/npc_cpt_faction_e_01.png': require('../../assets/images/npc/npc_cpt_faction_e_01.png'),
  'assets/images/npc/npc_cpt_faction_e_02.png': require('../../assets/images/npc/npc_cpt_faction_e_02.png'),
  'assets/images/npc/npc_cpt_faction_e_03.png': require('../../assets/images/npc/npc_cpt_faction_e_03.png'),
  'assets/images/npc/npc_cpt_faction_e_04.png': require('../../assets/images/npc/npc_cpt_faction_e_04.png'),
  'assets/images/npc/npc_cpt_faction_e_05.png': require('../../assets/images/npc/npc_cpt_faction_e_05.png'),
  'assets/images/npc/npc_cpt_faction_e_06.png': require('../../assets/images/npc/npc_cpt_faction_e_06.png'),
  'assets/images/npc/npc_cpt_faction_e_07.png': require('../../assets/images/npc/npc_cpt_faction_e_07.png'),
  'assets/images/npc/npc_cpt_faction_e_08.png': require('../../assets/images/npc/npc_cpt_faction_e_08.png'),
  'assets/images/npc/npc_cpt_faction_e_09.png': require('../../assets/images/npc/npc_cpt_faction_e_09.png'),
  'assets/images/npc/npc_cpt_faction_e_10.png': require('../../assets/images/npc/npc_cpt_faction_e_10.png'),
  'assets/images/npc/npc_cpt_faction_e_11.png': require('../../assets/images/npc/npc_cpt_faction_e_11.png'),
  'assets/images/npc/npc_cpt_faction_e_12.png': require('../../assets/images/npc/npc_cpt_faction_e_12.png'),
  'assets/images/npc/npc_cpt_faction_n_01.png': require('../../assets/images/npc/npc_cpt_faction_n_01.png'),
  'assets/images/npc/npc_cpt_faction_n_02.png': require('../../assets/images/npc/npc_cpt_faction_n_02.png'),
  'assets/images/npc/npc_cpt_faction_n_03.png': require('../../assets/images/npc/npc_cpt_faction_n_03.png'),
  'assets/images/npc/npc_cpt_faction_n_04.png': require('../../assets/images/npc/npc_cpt_faction_n_04.png'),
  'assets/images/npc/npc_cpt_faction_n_05.png': require('../../assets/images/npc/npc_cpt_faction_n_05.png'),
  'assets/images/npc/npc_cpt_faction_n_06.png': require('../../assets/images/npc/npc_cpt_faction_n_06.png'),
  'assets/images/npc/npc_cpt_faction_n_07.png': require('../../assets/images/npc/npc_cpt_faction_n_07.png'),
  'assets/images/npc/npc_cpt_faction_n_08.png': require('../../assets/images/npc/npc_cpt_faction_n_08.png'),
  'assets/images/npc/npc_cpt_faction_n_09.png': require('../../assets/images/npc/npc_cpt_faction_n_09.png'),
  'assets/images/npc/npc_cpt_faction_n_10.png': require('../../assets/images/npc/npc_cpt_faction_n_10.png'),
  'assets/images/npc/npc_cpt_faction_n_11.png': require('../../assets/images/npc/npc_cpt_faction_n_11.png'),
  'assets/images/npc/npc_cpt_faction_n_12.png': require('../../assets/images/npc/npc_cpt_faction_n_12.png'),
  'assets/images/npc/npc_cpt_faction_s_01.png': require('../../assets/images/npc/npc_cpt_faction_s_01.png'),
  'assets/images/npc/npc_cpt_faction_s_02.png': require('../../assets/images/npc/npc_cpt_faction_s_02.png'),
  'assets/images/npc/npc_cpt_faction_s_03.png': require('../../assets/images/npc/npc_cpt_faction_s_03.png'),
  'assets/images/npc/npc_cpt_faction_s_04.png': require('../../assets/images/npc/npc_cpt_faction_s_04.png'),
  'assets/images/npc/npc_cpt_faction_s_05.png': require('../../assets/images/npc/npc_cpt_faction_s_05.png'),
  'assets/images/npc/npc_cpt_faction_s_06.png': require('../../assets/images/npc/npc_cpt_faction_s_06.png'),
  'assets/images/npc/npc_cpt_faction_s_07.png': require('../../assets/images/npc/npc_cpt_faction_s_07.png'),
  'assets/images/npc/npc_cpt_faction_s_08.png': require('../../assets/images/npc/npc_cpt_faction_s_08.png'),
  'assets/images/npc/npc_cpt_faction_s_09.png': require('../../assets/images/npc/npc_cpt_faction_s_09.png'),
  'assets/images/npc/npc_cpt_faction_s_10.png': require('../../assets/images/npc/npc_cpt_faction_s_10.png'),
  'assets/images/npc/npc_cpt_faction_s_11.png': require('../../assets/images/npc/npc_cpt_faction_s_11.png'),
  'assets/images/npc/npc_cpt_faction_s_12.png': require('../../assets/images/npc/npc_cpt_faction_s_12.png'),
  'assets/images/npc/npc_cpt_faction_w_01.png': require('../../assets/images/npc/npc_cpt_faction_w_01.png'),
  'assets/images/npc/npc_cpt_faction_w_02.png': require('../../assets/images/npc/npc_cpt_faction_w_02.png'),
  'assets/images/npc/npc_cpt_faction_w_03.png': require('../../assets/images/npc/npc_cpt_faction_w_03.png'),
  'assets/images/npc/npc_cpt_faction_w_04.png': require('../../assets/images/npc/npc_cpt_faction_w_04.png'),
  'assets/images/npc/npc_cpt_faction_w_05.png': require('../../assets/images/npc/npc_cpt_faction_w_05.png'),
  'assets/images/npc/npc_cpt_faction_w_06.png': require('../../assets/images/npc/npc_cpt_faction_w_06.png'),
  'assets/images/npc/npc_cpt_faction_w_07.png': require('../../assets/images/npc/npc_cpt_faction_w_07.png'),
  'assets/images/npc/npc_cpt_faction_w_08.png': require('../../assets/images/npc/npc_cpt_faction_w_08.png'),
  'assets/images/npc/npc_cpt_faction_w_09.png': require('../../assets/images/npc/npc_cpt_faction_w_09.png'),
  'assets/images/npc/npc_cpt_faction_w_10.png': require('../../assets/images/npc/npc_cpt_faction_w_10.png'),
  'assets/images/npc/npc_cpt_faction_w_11.png': require('../../assets/images/npc/npc_cpt_faction_w_11.png'),
  'assets/images/npc/npc_cpt_faction_w_12.png': require('../../assets/images/npc/npc_cpt_faction_w_12.png'),
  'assets/images/npc/npc_cpt_gov_genesis.png': require('../../assets/images/npc/npc_cpt_gov_genesis.png'),
  'assets/images/npc/npc_cpt_gov_helios.png': require('../../assets/images/npc/npc_cpt_gov_helios.png'),
  'assets/images/npc/npc_cpt_gov_iron.png': require('../../assets/images/npc/npc_cpt_gov_iron.png'),
  'assets/images/npc/npc_cpt_gov_minerva.png': require('../../assets/images/npc/npc_cpt_gov_minerva.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_01.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_01.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_02.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_02.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_03.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_03.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_04.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_04.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_05.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_05.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_06.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_06.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_07.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_07.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_08.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_08.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_09.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_09.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_10.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_10.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_11.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_11.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_12.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_12.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_13.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_13.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_14.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_14.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_15.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_15.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_16.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_16.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_17.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_17.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_18.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_18.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_19.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_19.png'),
  'assets/images/npc/npc_cpt_gov_reserve_blue_20.png': require('../../assets/images/npc/npc_cpt_gov_reserve_blue_20.png'),
  'assets/images/npc/npc_cpt_gov_reserve_neutral_01.png': require('../../assets/images/npc/npc_cpt_gov_reserve_neutral_01.png'),
  'assets/images/npc/npc_cpt_gov_reserve_neutral_02.png': require('../../assets/images/npc/npc_cpt_gov_reserve_neutral_02.png'),
  'assets/images/npc/npc_cpt_gov_reserve_neutral_03.png': require('../../assets/images/npc/npc_cpt_gov_reserve_neutral_03.png'),
  'assets/images/npc/npc_cpt_gov_reserve_neutral_04.png': require('../../assets/images/npc/npc_cpt_gov_reserve_neutral_04.png'),
  'assets/images/npc/npc_cpt_gov_reserve_neutral_05.png': require('../../assets/images/npc/npc_cpt_gov_reserve_neutral_05.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_01.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_01.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_02.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_02.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_03.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_03.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_04.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_04.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_05.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_05.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_06.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_06.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_07.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_07.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_08.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_08.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_09.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_09.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_10.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_10.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_11.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_11.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_12.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_12.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_13.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_13.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_14.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_14.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_15.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_15.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_16.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_16.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_17.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_17.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_18.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_18.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_19.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_19.png'),
  'assets/images/npc/npc_cpt_gov_reserve_red_20.png': require('../../assets/images/npc/npc_cpt_gov_reserve_red_20.png'),
  'assets/images/npc/npc_cpt_jex.png': require('../../assets/images/npc/npc_cpt_jex.png'),
  'assets/images/npc/npc_cpt_kresh.png': require('../../assets/images/npc/npc_cpt_kresh.png'),
  'assets/images/npc/npc_cpt_mireille.png': require('../../assets/images/npc/npc_cpt_mireille.png'),
  'assets/images/npc/npc_cpt_mock_pvp_01.png': require('../../assets/images/npc/npc_cpt_mock_pvp_01.png'),
  'assets/images/npc/npc_cpt_mock_pvp_02.png': require('../../assets/images/npc/npc_cpt_mock_pvp_02.png'),
  'assets/images/npc/npc_cpt_mock_pvp_03.png': require('../../assets/images/npc/npc_cpt_mock_pvp_03.png'),
  'assets/images/npc/npc_cpt_mock_pvp_04.png': require('../../assets/images/npc/npc_cpt_mock_pvp_04.png'),
  'assets/images/npc/npc_cpt_mock_pvp_05.png': require('../../assets/images/npc/npc_cpt_mock_pvp_05.png'),
  'assets/images/npc/npc_cpt_mock_pvp_06.png': require('../../assets/images/npc/npc_cpt_mock_pvp_06.png'),
  'assets/images/npc/npc_cpt_mock_pvp_07.png': require('../../assets/images/npc/npc_cpt_mock_pvp_07.png'),
  'assets/images/npc/npc_cpt_mock_pvp_08.png': require('../../assets/images/npc/npc_cpt_mock_pvp_08.png'),
  'assets/images/npc/npc_cpt_mock_pvp_09.png': require('../../assets/images/npc/npc_cpt_mock_pvp_09.png'),
  'assets/images/npc/npc_cpt_mock_pvp_10.png': require('../../assets/images/npc/npc_cpt_mock_pvp_10.png'),
  'assets/images/npc/npc_cpt_mock_pvp_11.png': require('../../assets/images/npc/npc_cpt_mock_pvp_11.png'),
  'assets/images/npc/npc_cpt_mock_pvp_12.png': require('../../assets/images/npc/npc_cpt_mock_pvp_12.png'),
  'assets/images/npc/npc_cpt_mock_pvp_13.png': require('../../assets/images/npc/npc_cpt_mock_pvp_13.png'),
  'assets/images/npc/npc_cpt_mock_pvp_14.png': require('../../assets/images/npc/npc_cpt_mock_pvp_14.png'),
  'assets/images/npc/npc_cpt_mock_pvp_15.png': require('../../assets/images/npc/npc_cpt_mock_pvp_15.png'),
  'assets/images/npc/npc_cpt_mock_pvp_16.png': require('../../assets/images/npc/npc_cpt_mock_pvp_16.png'),
  'assets/images/npc/npc_cpt_mock_pvp_17.png': require('../../assets/images/npc/npc_cpt_mock_pvp_17.png'),
  'assets/images/npc/npc_cpt_mock_pvp_18.png': require('../../assets/images/npc/npc_cpt_mock_pvp_18.png'),
  'assets/images/npc/npc_cpt_mock_pvp_19.png': require('../../assets/images/npc/npc_cpt_mock_pvp_19.png'),
  'assets/images/npc/npc_cpt_neweden_blue_07.png': require('../../assets/images/npc/npc_cpt_neweden_blue_07.png'),
  'assets/images/npc/npc_cpt_neweden_red_07.png': require('../../assets/images/npc/npc_cpt_neweden_red_07.png'),
  'assets/images/npc/npc_cpt_orin.png': require('../../assets/images/npc/npc_cpt_orin.png'),
  'assets/images/npc/npc_cpt_raid_scar.png': require('../../assets/images/npc/npc_cpt_raid_scar.png'),
  'assets/images/npc/npc_cpt_sela.png': require('../../assets/images/npc/npc_cpt_sela.png'),
  'assets/images/npc/npc_cpt_solar_guard_01.png': require('../../assets/images/npc/npc_cpt_solar_guard_01.png'),
  'assets/images/npc/npc_cpt_solar_guard_02.png': require('../../assets/images/npc/npc_cpt_solar_guard_02.png'),
  'assets/images/npc/npc_cpt_sq_cal_ridge.png': require('../../assets/images/npc/npc_cpt_sq_cal_ridge.png'),
  'assets/images/npc/npc_cpt_sq_ivy_kenn.png': require('../../assets/images/npc/npc_cpt_sq_ivy_kenn.png'),
  'assets/images/npc/npc_cpt_sq_kade_rim.png': require('../../assets/images/npc/npc_cpt_sq_kade_rim.png'),
  'assets/images/npc/npc_cpt_sq_kett_mion.png': require('../../assets/images/npc/npc_cpt_sq_kett_mion.png'),
  'assets/images/npc/npc_cpt_sq_lira_mon.png': require('../../assets/images/npc/npc_cpt_sq_lira_mon.png'),
  'assets/images/npc/npc_cpt_sq_nila_shol.png': require('../../assets/images/npc/npc_cpt_sq_nila_shol.png'),
  'assets/images/npc/npc_cpt_sq_noll_pass.png': require('../../assets/images/npc/npc_cpt_sq_noll_pass.png'),
  'assets/images/npc/npc_cpt_sq_orren_bask.png': require('../../assets/images/npc/npc_cpt_sq_orren_bask.png'),
  'assets/images/npc/npc_cpt_sq_rhea_vin.png': require('../../assets/images/npc/npc_cpt_sq_rhea_vin.png'),
  'assets/images/npc/npc_cpt_sq_tolin_grave.png': require('../../assets/images/npc/npc_cpt_sq_tolin_grave.png'),
  'assets/images/npc/npc_cpt_sq_veil_hook.png': require('../../assets/images/npc/npc_cpt_sq_veil_hook.png'),
  'assets/images/npc/npc_cpt_story_darel_sosa.png': require('../../assets/images/npc/npc_cpt_story_darel_sosa.png'),
  'assets/images/npc/npc_cpt_story_ian_koval.png': require('../../assets/images/npc/npc_cpt_story_ian_koval.png'),
  'assets/images/npc/npc_cpt_story_noah_frick.png': require('../../assets/images/npc/npc_cpt_story_noah_frick.png'),
  'assets/images/npc/npc_cpt_vector.png': require('../../assets/images/npc/npc_cpt_vector.png'),
  'assets/images/npc/npc_cpt_vega_blue_07.png': require('../../assets/images/npc/npc_cpt_vega_blue_07.png'),
  'assets/images/npc/npc_cpt_vega_blue_08.png': require('../../assets/images/npc/npc_cpt_vega_blue_08.png'),
  'assets/images/npc/npc_cpt_vega_blue_09.png': require('../../assets/images/npc/npc_cpt_vega_blue_09.png'),
  'assets/images/npc/npc_cpt_vega_blue_10.png': require('../../assets/images/npc/npc_cpt_vega_blue_10.png'),
  'assets/images/npc/npc_cpt_vega_blue_11.png': require('../../assets/images/npc/npc_cpt_vega_blue_11.png'),
  'assets/images/npc/npc_cpt_vega_red_04.png': require('../../assets/images/npc/npc_cpt_vega_red_04.png'),
  'assets/images/npc/npc_cpt_vega_red_05.png': require('../../assets/images/npc/npc_cpt_vega_red_05.png'),
  'assets/images/npc/npc_cpt_vega_red_06.png': require('../../assets/images/npc/npc_cpt_vega_red_06.png'),
  'assets/images/npc/npc_cpt_vega_red_07.png': require('../../assets/images/npc/npc_cpt_vega_red_07.png'),
  'assets/images/npc/npc_cpt_vega_red_08.png': require('../../assets/images/npc/npc_cpt_vega_red_08.png'),
  'assets/images/npc/npc_cpt_vega_red_09.png': require('../../assets/images/npc/npc_cpt_vega_red_09.png'),
  'assets/images/npc/npc_cpt_vega_red_10.png': require('../../assets/images/npc/npc_cpt_vega_red_10.png'),
  'assets/images/npc/npc_cpt_vega_red_11.png': require('../../assets/images/npc/npc_cpt_vega_red_11.png'),
  'assets/images/npc/npc_cpt_vega_red_12.png': require('../../assets/images/npc/npc_cpt_vega_red_12.png'),
  'assets/images/npc/npc_cpt_vega_test_a.png': require('../../assets/images/npc/npc_cpt_vega_test_a.png'),
  'assets/images/npc/npc_cpt_vega_test_b.png': require('../../assets/images/npc/npc_cpt_vega_test_b.png'),
  'assets/images/npc/npc_cpt_vega_watch_01.png': require('../../assets/images/npc/npc_cpt_vega_watch_01.png'),
  'assets/images/npc/npc_cpt_vega_watch_02.png': require('../../assets/images/npc/npc_cpt_vega_watch_02.png'),
};

export function resolveNpcCaptainPortraitSource(
  key: string | undefined | null,
): ImageSourcePropType | null {
  if (key == null) return null;
  const k = String(key).trim();
  if (!k) return null;
  return NPC_CAPTAIN_PORTRAIT_BY_ASSET_KEY[k] ?? null;
}

export function listNpcCaptainPortraitSources(): ImageSourcePropType[] {
  return Object.values(NPC_CAPTAIN_PORTRAIT_BY_ASSET_KEY);
}

export function resolveNpcCaptainPortraitAspectRatio(
  source: ImageSourcePropType | null | undefined,
): number | null {
  if (source == null) return null;
  const resolved = Image.resolveAssetSource(source);
  const w = resolved?.width;
  const h = resolved?.height;
  if (!w || !h) return null;
  return w / h;
}
