// AUTO-GENERATED by tools/content-tables/build-content-from-csv.mjs
/** Table-First 정본: tables/content/mission_time_limit_policy.csv */
export type MissionTimeLimitPolicyRow = {
  track: string;
  playCategory: string;
  timeLimitHours: number;
};

export const MISSION_TIME_LIMIT_POLICY_FROM_CSV: MissionTimeLimitPolicyRow[] = [
  { track: "tutorial", playCategory: "*", timeLimitHours: 0 },
  { track: "main_story", playCategory: "*", timeLimitHours: 0 },
  { track: "quest", playCategory: "combat", timeLimitHours: 24 },
  { track: "quest", playCategory: "delivery", timeLimitHours: 72 },
  { track: "quest", playCategory: "travel", timeLimitHours: 48 },
  { track: "quest", playCategory: "mixed", timeLimitHours: 48 },
  { track: "quest", playCategory: "event", timeLimitHours: 48 },
  { track: "inst_tpl", playCategory: "combat", timeLimitHours: 24 },
  { track: "inst_tpl", playCategory: "delivery", timeLimitHours: 72 },
  { track: "inst_tpl", playCategory: "travel", timeLimitHours: 48 },
  { track: "inst_tpl", playCategory: "mixed", timeLimitHours: 48 },
  { track: "inst_tpl", playCategory: "event", timeLimitHours: 48 }
];
