/**
 * 여권형 신분증 초상 슬롯 — 파일럿 정보창·행성 총사령관 카드 공통.
 * 슬롯은 NPC 초상 정본(240×240)과 같이 정사각형. cover/contain 동일.
 */
import {
  NPC_PORTRAIT_CANONICAL_HEIGHT_PX,
  NPC_PORTRAIT_CANONICAL_WIDTH_PX,
} from '../game/npcPortraitPixelContract';

export const PASSPORT_IDENTITY_CARD_HEIGHT_PX = 156;
export const PASSPORT_IDENTITY_DOC_HEADER_PX = 22;
export const PASSPORT_IDENTITY_BODY_HEIGHT_PX =
  PASSPORT_IDENTITY_CARD_HEIGHT_PX - PASSPORT_IDENTITY_DOC_HEADER_PX;

/** NPC 초상 정본 240×240 */
export const PASSPORT_IDENTITY_PHOTO_NATIVE_WIDTH_PX = NPC_PORTRAIT_CANONICAL_WIDTH_PX;
export const PASSPORT_IDENTITY_PHOTO_NATIVE_HEIGHT_PX = NPC_PORTRAIT_CANONICAL_HEIGHT_PX;
export const PASSPORT_IDENTITY_PHOTO_ASPECT =
  PASSPORT_IDENTITY_PHOTO_NATIVE_WIDTH_PX / PASSPORT_IDENTITY_PHOTO_NATIVE_HEIGHT_PX;

export const PASSPORT_IDENTITY_PHOTO_WIDTH_PX = PASSPORT_IDENTITY_BODY_HEIGHT_PX;

export function resolvePassportIdentityPhotoWidthPx(): number {
  return PASSPORT_IDENTITY_PHOTO_WIDTH_PX;
}
