import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { STAR_SYSTEMS_FROM_CSV } from '../../src/data/generated/csvSystems';
import { buildNebulaProfile } from '../../src/game/planetNebulaProfile';
import {
  PLANET_NEBULA_BAKE_SIZE_PX,
  nebulaProfileToBakeUniforms,
  samplePlanetNebulaRgba,
} from '../../src/game/planetNebulaBakeSample';

const ROOT = path.resolve(__dirname, '../..');
const OUT_DIR = path.join(ROOT, 'assets/images/nebula/baked');
const REGISTRY_PATH = path.join(ROOT, 'src/data/generated/planetNebulaBakedAssets.ts');

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });

  const entries: Array<{ planetId: string; relKey: string }> = [];
  for (const system of Object.values(STAR_SYSTEMS_FROM_CSV)) {
    if (system.planets.length === 0) continue;
    for (const planet of system.planets) {
      if (planet.mainStageSkiaNebulaEnabled === false) continue;
      const profile = buildNebulaProfile(planet, system.zone);
      const uniforms = nebulaProfileToBakeUniforms(profile);
      const size = PLANET_NEBULA_BAKE_SIZE_PX;
      const buf = Buffer.alloc(size * size * 4);
      for (let y = 0; y < size; y += 1) {
        for (let x = 0; x < size; x += 1) {
          const [r, g, b, a] = samplePlanetNebulaRgba(x, y, size, uniforms, 0);
          const i = (y * size + x) * 4;
          buf[i] = Math.round(r * 255);
          buf[i + 1] = Math.round(g * 255);
          buf[i + 2] = Math.round(b * 255);
          buf[i + 3] = Math.round(a * 255);
        }
      }
      const outPath = path.join(OUT_DIR, `${planet.id}.png`);
      await sharp(buf, { raw: { width: size, height: size, channels: 4 } })
        .png({ compressionLevel: 9 })
        .toFile(outPath);
      entries.push({
        planetId: planet.id,
        relKey: `assets/images/nebula/baked/${planet.id}.png`,
      });
      console.log(`Baked: ${planet.id}`);
    }
  }

  entries.sort((a, b) => a.planetId.localeCompare(b.planetId));
  const lines = entries.map(
    (e) =>
      `  ${JSON.stringify(e.planetId)}: require('../../../${e.relKey.replace(/\\/g, '/')}'),`,
  );
  const registry = `// AUTO-GENERATED by tools/planet-nebula-bake/bake-planet-nebula-images.ts
import type { ImageSourcePropType } from 'react-native';

export const PLANET_NEBULA_BAKED_BY_PLANET_ID: Record<string, ImageSourcePropType> = {
${lines.join('\n')}
};
`;
  await fs.writeFile(REGISTRY_PATH, registry, 'utf8');
  console.log(`Registry: ${REGISTRY_PATH}`);
  console.log(`Done — ${entries.length} planet nebula bakes.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
