import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {
  PLANET_GLOBE_LOOK_CANON,
  assertPlanetGlobeLooksUniqueness,
  type PlanetGlobeBakeKind,
  type PlanetGlobeLookRow,
  type PlanetGlobeVariant,
  type Rgb01,
} from '../../src/game/planetGlobeLookCanon';
import {
  deriveColonizedGlobeLook,
  seedColonizedLookUniquenessState,
} from '../../src/game/planetGlobeLookDerive';
import { PLANET_GLOBE_BAKE_SIZE_PX, samplePlanetGlobeLookRgba } from '../../src/game/planetGlobeBakeSample';
import { listColonizedSynthPlanetTargets } from './listColonizedSynthPlanets';

const ROOT = path.resolve(__dirname, '../..');
const OUT_DIR = path.join(ROOT, 'assets/images/planet/baked');
const REGISTRY_PATH = path.join(ROOT, 'src/data/generated/planetGlobeBakedAssets.ts');
const IDS_PATH = path.join(ROOT, 'src/data/generated/planetGlobeBakedPlanetIds.ts');
const COLONIZED_LOOK_PATH = path.join(ROOT, 'src/data/generated/planetGlobeLookColonized.ts');
const THUMB = 16;
/** 같은 kind 16×16 썸네일 L2 (0–255). 이하면 형제 복제 판정 */
const MIN_KIND_THUMB_L2 = 22;

function bakeBuffer(row: PlanetGlobeLookRow): Buffer {
  const size = PLANET_GLOBE_BAKE_SIZE_PX;
  const buf = Buffer.alloc(size * size * 4);
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const [r, g, b, a] = samplePlanetGlobeLookRgba(row, x, y, size);
      const i = (y * size + x) * 4;
      buf[i] = Math.round(r * 255);
      buf[i + 1] = Math.round(g * 255);
      buf[i + 2] = Math.round(b * 255);
      buf[i + 3] = Math.round(a * 255);
    }
  }
  return buf;
}

function thumbMean(buf: Buffer, size: number): Float32Array {
  const out = new Float32Array(THUMB * THUMB * 3);
  const cell = size / THUMB;
  for (let ty = 0; ty < THUMB; ty += 1) {
    for (let tx = 0; tx < THUMB; tx += 1) {
      let r = 0;
      let g = 0;
      let b = 0;
      let n = 0;
      const x0 = Math.floor(tx * cell);
      const y0 = Math.floor(ty * cell);
      const x1 = Math.floor((tx + 1) * cell);
      const y1 = Math.floor((ty + 1) * cell);
      for (let y = y0; y < y1; y += 1) {
        for (let x = x0; x < x1; x += 1) {
          const i = (y * size + x) * 4;
          if ((buf[i + 3] ?? 0) < 16) continue;
          r += buf[i] ?? 0;
          g += buf[i + 1] ?? 0;
          b += buf[i + 2] ?? 0;
          n += 1;
        }
      }
      const o = (ty * THUMB + tx) * 3;
      if (n > 0) {
        out[o] = r / n;
        out[o + 1] = g / n;
        out[o + 2] = b / n;
      }
    }
  }
  return out;
}

function thumbL2(a: Float32Array, b: Float32Array): number {
  let s = 0;
  for (let i = 0; i < a.length; i += 1) {
    const d = (a[i] ?? 0) - (b[i] ?? 0);
    s += d * d;
  }
  return Math.sqrt(s / (THUMB * THUMB));
}

function assertBakedKindUniqueness(
  baked: Array<{ planetId: string; kind: PlanetGlobeBakeKind; thumb: Float32Array }>,
): void {
  for (let i = 0; i < baked.length; i += 1) {
    for (let j = i + 1; j < baked.length; j += 1) {
      const a = baked[i]!;
      const b = baked[j]!;
      if (a.kind !== b.kind) continue;
      const d = thumbL2(a.thumb, b.thumb);
      if (d < MIN_KIND_THUMB_L2) {
        throw new Error(
          `look-clone: ${a.planetId} ≈ ${b.planetId} (${a.kind}) thumbL2=${d.toFixed(2)} < ${MIN_KIND_THUMB_L2}`,
        );
      }
    }
  }
}

function rgbLit(c: Rgb01): string {
  return `[${c[0]}, ${c[1]}, ${c[2]}]`;
}

function variantLit(v: PlanetGlobeVariant): string {
  return `{
      lightX: ${v.lightX}, lightY: ${v.lightY}, lightZ: ${v.lightZ}, rotDeg: ${v.rotDeg}, ox: ${v.ox}, oy: ${v.oy}, scale: ${v.scale},
      cloudLo: ${v.cloudLo}, cloudHi: ${v.cloudHi}, landLo: ${v.landLo}, landHi: ${v.landHi}, extra: ${v.extra},
      c0: ${rgbLit(v.c0)}, c1: ${rgbLit(v.c1)}, c2: ${rgbLit(v.c2)},
      c3: ${rgbLit(v.c3)}, c4: ${rgbLit(v.c4)},
      atmo: ${rgbLit(v.atmo)}, rim: ${rgbLit(v.rim)},
    }`;
}

function colonizedLooksSource(asOfDayKey: string, rows: readonly PlanetGlobeLookRow[]): string {
  const body = rows
    .map(
      (row) => `  {
    planetId: ${JSON.stringify(row.planetId)},
    kind: ${JSON.stringify(row.kind)},
    seed: ${row.seed},
    variant: ${variantLit(row.variant)},
  }`,
    )
    .join(',\n');
  return `// AUTO-GENERATED by tools/planet-globe-bake/bake-core-planet-globes.ts
import type { PlanetGlobeLookRow } from '../../game/planetGlobeLookCanon';

export const PLANET_GLOBE_COLONIZED_AS_OF_DAY_KEY = ${JSON.stringify(asOfDayKey)};
export const PLANET_GLOBE_LOOK_COLONIZED: readonly PlanetGlobeLookRow[] = [
${body}
];
`;
}

async function writePng(row: PlanetGlobeLookRow): Promise<Buffer> {
  const buf = bakeBuffer(row);
  const outPath = path.join(OUT_DIR, `${row.planetId}.png`);
  await sharp(buf, { raw: { width: PLANET_GLOBE_BAKE_SIZE_PX, height: PLANET_GLOBE_BAKE_SIZE_PX, channels: 4 } })
    .png({ compressionLevel: 9 })
    .toFile(outPath);
  return buf;
}

async function thumbFromExistingPng(planetId: string): Promise<Float32Array | null> {
  const outPath = path.join(OUT_DIR, `${planetId}.png`);
  try {
    const { data, info } = await sharp(outPath).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
    return thumbMean(data, info.width);
  } catch {
    return null;
  }
}

async function main() {
  const { asOfDayKey, policyEpoch, targets } = listColonizedSynthPlanetTargets();
  const coreIds = new Set(PLANET_GLOBE_LOOK_CANON.map((r) => r.planetId));
  const uniqTargets = targets.filter((t) => !coreIds.has(t.planetId));
  const { usedSeeds, usedFingerprintsByKind } = seedColonizedLookUniquenessState(PLANET_GLOBE_LOOK_CANON);
  const colonizedLooks: PlanetGlobeLookRow[] = [];
  for (const t of uniqTargets) {
    colonizedLooks.push(
      deriveColonizedGlobeLook(t.planetId, t.zone, usedSeeds, usedFingerprintsByKind),
    );
  }
  assertPlanetGlobeLooksUniqueness([...PLANET_GLOBE_LOOK_CANON, ...colonizedLooks]);

  await fs.mkdir(OUT_DIR, { recursive: true });
  const entries: Array<{ planetId: string; relKey: string }> = [];
  const baked: Array<{ planetId: string; kind: PlanetGlobeBakeKind; thumb: Float32Array }> = [];

  for (const row of PLANET_GLOBE_LOOK_CANON) {
    let thumb = await thumbFromExistingPng(row.planetId);
    if (!thumb) {
      const buf = await writePng(row);
      thumb = thumbMean(buf, PLANET_GLOBE_BAKE_SIZE_PX);
      console.log(`Baked core: ${row.planetId} (${row.kind})`);
    } else {
      console.log(`Reuse core: ${row.planetId} (${row.kind})`);
    }
    baked.push({ planetId: row.planetId, kind: row.kind, thumb });
    entries.push({ planetId: row.planetId, relKey: `assets/images/planet/baked/${row.planetId}.png` });
  }

  for (let i = 0; i < colonizedLooks.length; i += 1) {
    const zone = uniqTargets.find((t) => t.planetId === colonizedLooks[i]!.planetId)?.zone ?? 'neutral';
    let current = colonizedLooks[i]!;
    let accepted: Float32Array | null = null;
    for (let retry = 0; retry < 8; retry += 1) {
      if (retry > 0) {
        current = deriveColonizedGlobeLook(current.planetId, zone, usedSeeds, usedFingerprintsByKind);
      }
      const buf = await writePng(current);
      const thumb = thumbMean(buf, PLANET_GLOBE_BAKE_SIZE_PX);
      const clash = baked.find(
        (b) => b.kind === current.kind && thumbL2(b.thumb, thumb) < MIN_KIND_THUMB_L2,
      );
      if (!clash) {
        accepted = thumb;
        colonizedLooks[i] = current;
        break;
      }
      console.log(`retry ${current.planetId} ≈ ${clash.planetId} — rederive`);
    }
    if (!accepted) {
      throw new Error(`look-clone persist: ${current.planetId}`);
    }
    baked.push({ planetId: current.planetId, kind: current.kind, thumb: accepted });
    entries.push({ planetId: current.planetId, relKey: `assets/images/planet/baked/${current.planetId}.png` });
    console.log(`Baked colonized: ${current.planetId} (${current.kind})`);
  }

  assertBakedKindUniqueness(baked);
  await fs.writeFile(COLONIZED_LOOK_PATH, colonizedLooksSource(asOfDayKey, colonizedLooks), 'utf8');

  entries.sort((a, b) => a.planetId.localeCompare(b.planetId));
  const lines = entries.map(
    (e) => `  ${JSON.stringify(e.planetId)}: require('../../../${e.relKey.replace(/\\/g, '/')}'),`,
  );
  const registry = `// AUTO-GENERATED by tools/planet-globe-bake/bake-core-planet-globes.ts
import type { ImageSourcePropType } from 'react-native';

export const PLANET_GLOBE_BAKED_BY_PLANET_ID: Record<string, ImageSourcePropType> = {
${lines.join('\n')}
};
`;
  await fs.writeFile(REGISTRY_PATH, registry, 'utf8');
  const idLines = entries.map((e) => `  ${JSON.stringify(e.planetId)},`).join('\n');
  await fs.writeFile(
    IDS_PATH,
    `// AUTO-GENERATED by tools/planet-globe-bake/bake-core-planet-globes.ts
export const PLANET_GLOBE_BAKED_PLANET_IDS: readonly string[] = [
${idLines}
];
`,
    'utf8',
  );
  console.log(`Registry: ${REGISTRY_PATH}`);
  console.log(
    `Done — core=${PLANET_GLOBE_LOOK_CANON.length} colonized=${colonizedLooks.length} epoch=${policyEpoch} asOf=${asOfDayKey}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
