// planet hub styles — extracted from app/(game)/planet.tsx
import { Platform, StyleSheet } from 'react-native';
import { COLORS, FONTS, SPACING } from '../../../utils/theme';
import { TACTICAL_HUB } from '../../../ui/tactical/tacticalHubTokens';
import {
  PLANET_MAIN_BACKGROUND_CLAN_PLATE_AFTER_NAME_GAP_PX,
  PLANET_MAIN_BACKGROUND_CLAN_PLATE_OFFSET_X_PX,
  PLANET_MAIN_BACKGROUND_CLAN_PLATE_OFFSET_Y_PX,
  PLANET_MAIN_BACKGROUND_CLAN_PLATE_SLOT_HEIGHT_PX,
  PLANET_MAIN_BACKGROUND_SYSTEM_NAME_MIN_HEIGHT_PX,
  PLANET_MAIN_BOTTOM_FEATURE_RESERVE_PX,
  PLANET_MAIN_ORBIT_SCENE_SIZE as ORBIT_SCENE_SIZE,
  PLANET_MAIN_TOPBAR_BORDER_BOTTOM_PX,
  PLANET_MAIN_TOPBAR_ICON_BORDER_RADIUS,
  PLANET_MAIN_TOPBAR_ICON_BUTTON_PX,
  PLANET_MAIN_TOPBAR_PADDING_HORIZONTAL,
  PLANET_MAIN_TOPBAR_PADDING_VERTICAL,
} from '../../../stages/planetMainStageLayout';
import {
  INFO_LOG_CONTENT_PAD_BOTTOM,
  INFO_LOG_LINE_HEIGHT_PX,
  INFO_LOG_ROW_GAP_PX,
  PLANET_HUB_CAPITAL_COMBAT_DIM_OPACITY,
  PLANET_HUB_CAPITAL_COMBAT_GRAY,
  PLANET_MAIN_COMBAT_LAYER_HEIGHT_SCALE_Y,
  PLANET_MAIN_COMBAT_LAYER_WIDTH_SCALE_X,
  MINING_GUIDE_LABEL_PAST_TIP_PX,
  MINING_GUIDE_LINE_RUN_PX,
  WORLD_OBJECT_ANCHOR_PX,
  WORLD_OBJECT_DEFENSE_SATELLITE_COLOR,
  WORLD_OBJECT_DEFENSE_SATELLITE_MARK_PX,
  WORLD_OBJECT_DEFENSE_ZONE_STROKE,
  WORLD_OBJECT_WRECK_MARK_PX,
  WORLD_OBJECT_WRECK_STROKE_COLOR,
} from '../../../game/planetHub/planetHubConstants';
export const planetHubStyles = StyleSheet.create({
  stageRoot: { flex: 1, position: 'relative' },
  foreground: {
    ...StyleSheet.absoluteFillObject,
    flexDirection: 'column',
  },
  mainArea: {
    flex: 1,
    minHeight: 0,
    position: 'relative',
    flexDirection: 'column',
  },
  planetBottomDock: {
    width: '100%',
    zIndex: 15,
    backgroundColor: 'transparent',
  },
  scroll: { flex: 1 },
  /** Android 등에서 스크롤 기본 불투명 레이어가 배경 궤도를 덮는 경우 방지 */
  scrollTransparent: { backgroundColor: 'transparent' },
  scrollContent: {
    flexGrow: 1,
  },
  infoOverlaySlot: {
    position: 'absolute',
    right: SPACING.xs,
    top: SPACING.xs,
    zIndex: 20,
    elevation: 20,
    maxWidth: '42%',
  },
  edenCombatHudSlot: {
    position: 'absolute',
    left: 4,
    right: 4,
    zIndex: 11,
  },
  battleReadyOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '22%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 12,
  },
  battleReadyText: {
    fontFamily: FONTS.mono,
    fontSize: Math.max(9, Math.floor(FONTS.size.lg * 0.5)),
    fontWeight: FONTS.weight.bold,
    color: '#FF4D4D',
    letterSpacing: 1.2,
    textShadowColor: 'rgba(32,0,0,0.65)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  battleReadyTextBlinkOn: {
    opacity: 1,
  },
  battleReadyTextBlinkOff: {
    opacity: 0.25,
  },
  battleReadyCounter: {
    marginTop: 4,
    fontFamily: FONTS.mono,
    fontSize: Math.max(8, Math.floor(FONTS.size.md * 0.5)),
    color: '#FF8A8A',
    fontWeight: FONTS.weight.bold,
    textShadowColor: 'rgba(18,0,0,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  infoPanelWrap: {
    width: 112,
    flexShrink: 0,
    alignSelf: 'flex-end',
    borderWidth: 1,
    borderColor: 'rgba(120,132,160,0.35)',
    backgroundColor: 'rgba(12,18,32,0.42)',
    paddingLeft: SPACING.xs,
    paddingRight: 2,
    paddingTop: SPACING.xs,
    paddingBottom: SPACING.sm,
    borderRadius: 4,
    overflow: 'hidden',
  },
  infoPanelTitle: {
    fontFamily: FONTS.mono,
    fontSize: 9,
    color: COLORS.ink_faint,
    letterSpacing: 3,
    marginBottom: 4,
    textTransform: 'lowercase',
  },
  infoPanelWrapCapitalCombatMuted: {
    opacity: PLANET_HUB_CAPITAL_COMBAT_DIM_OPACITY,
    borderColor: 'rgba(130, 138, 150, 0.3)',
    backgroundColor: 'rgba(14, 18, 26, 0.34)',
  },
  infoPanelTitleCapitalCombatMuted: {
    color: PLANET_HUB_CAPITAL_COMBAT_GRAY.systemName,
  },
  infoInkCapitalCombatMuted: {
    color: PLANET_HUB_CAPITAL_COMBAT_GRAY.territory,
  },
  infoLogScroll: {
    flexGrow: 0,
  },
  infoLogContent: {
    paddingBottom: INFO_LOG_CONTENT_PAD_BOTTOM,
  },
  infoTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: INFO_LOG_ROW_GAP_PX,
    minHeight: INFO_LOG_LINE_HEIGHT_PX,
  },
  infoRowBullet: {
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: INFO_LOG_LINE_HEIGHT_PX,
    color: COLORS.ink_light,
  },
  infoNameMkCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  infoTableName: {
    flexShrink: 1,
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: INFO_LOG_LINE_HEIGHT_PX,
    color: COLORS.ink_light,
  },
  infoTableCaptain: {
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: INFO_LOG_LINE_HEIGHT_PX,
    color: COLORS.ink_light,
  },
  infoTableSep: {
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: INFO_LOG_LINE_HEIGHT_PX,
    color: COLORS.ink_faint,
    marginLeft: 3,
    marginRight: 2,
  },
  infoTableMk: {
    flexShrink: 0,
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: INFO_LOG_LINE_HEIGHT_PX,
    color: COLORS.ink_mid,
  },
  infoTableFull: {
    flex: 1,
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: INFO_LOG_LINE_HEIGHT_PX,
    color: COLORS.ink_light,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: PLANET_MAIN_TOPBAR_PADDING_HORIZONTAL,
    paddingVertical: PLANET_MAIN_TOPBAR_PADDING_VERTICAL,
    borderBottomWidth: PLANET_MAIN_TOPBAR_BORDER_BOTTOM_PX,
    borderBottomColor: TACTICAL_HUB.chromeBorder,
    backgroundColor: TACTICAL_HUB.chromeBg,
  },
  topBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: SPACING.xs,
    width: 112,
  },
  topBarRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    columnGap: SPACING.xs,
    minWidth: 128,
    flexShrink: 0,
  },
  topBarTitle: {
    flex: 1,
    textAlign: 'center',
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.md,
    fontWeight: FONTS.weight.bold,
    color: TACTICAL_HUB.chromeInk,
    letterSpacing: 1.2,
  },
  iconBtn: {
    width: PLANET_MAIN_TOPBAR_ICON_BUTTON_PX,
    height: PLANET_MAIN_TOPBAR_ICON_BUTTON_PX,
    borderRadius: PLANET_MAIN_TOPBAR_ICON_BORDER_RADIUS,
    borderWidth: 1,
    borderColor: TACTICAL_HUB.controlBtnBorder,
    backgroundColor: TACTICAL_HUB.controlBtnBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  currencyChip: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 3,
    maxWidth: 88,
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: PLANET_MAIN_TOPBAR_ICON_BORDER_RADIUS,
    borderWidth: 1,
    borderColor: TACTICAL_HUB.tileBorder,
    backgroundColor: TACTICAL_HUB.tileBg,
  },
  currencyChipGem: {},
  currencyChipCredits: {},
  currencyChipTextGem: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    fontWeight: FONTS.weight.bold,
    color: TACTICAL_HUB.topBarCurrencyInk,
    flexShrink: 1,
  },
  currencyChipTextCredits: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    fontWeight: FONTS.weight.bold,
    color: TACTICAL_HUB.topBarCurrencyInk,
    flexShrink: 1,
  },
  planetStageReserve: {
    width: '100%',
    backgroundColor: 'transparent',
  },
  planetOuter: {
    position: 'relative',
    overflow: 'hidden',
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bg_secondary,
  },
  /** 핵심 초상 — `planetInner`와 동일 지름(0.7×) 원 안에만 합성 */
  planetPortraitInnerWrap: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planetInner: {
    borderWidth: 1,
  },
  planetCoreGaugePanel: {
    position: 'absolute',
    width: 58,
    rowGap: 1,
    /** 행성 원·테두리 대비 시각적 중앙 보정 */
    transform: [{ translateX: 3 }],
  },
  planetCoreGaugeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 2,
  },
  planetCoreGaugeLabel: {
    width: 8,
    fontFamily: FONTS.mono,
    fontSize: 8,
    lineHeight: 10,
    fontWeight: FONTS.weight.bold,
    textAlign: 'center',
  },
  planetCoreGaugeSegWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 0,
    flex: 1,
  },
  planetCoreGaugeSeg: {
    width: 8,
    height: 3,
    borderWidth: 1,
    borderRadius: 1,
  },
  planetCoreGaugeSegOff: {
    backgroundColor: 'rgba(110,128,160,0.16)',
    borderColor: 'rgba(110,128,160,0.35)',
  },
  miningCard: {
    marginHorizontal: SPACING.md,
    marginTop: -2,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: TACTICAL_HUB.miningCardBorder,
    borderRadius: 10,
    backgroundColor: TACTICAL_HUB.miningCardBg,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    rowGap: 6,
  },
  miningHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    columnGap: SPACING.sm,
  },
  miningTitle: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.sm,
    fontWeight: FONTS.weight.bold,
    color: COLORS.ink_dark,
  },
  miningMeta: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: COLORS.ink_mid,
  },
  miningGuideLine: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: TACTICAL_HUB.miningGuideInk,
  },
  miningGaugeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
  },
  miningGaugeLabel: {
    width: 34,
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: COLORS.ink_mid,
  },
  miningGaugeSegments: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 2,
  },
  miningGaugeSeg: {
    flex: 1,
    height: 6,
    borderRadius: 2,
    borderWidth: 1,
  },
  miningGaugeSegOn: {
    backgroundColor: '#F5D86B',
    borderColor: '#FFE8A6',
  },
  miningGaugeSegOff: {
    backgroundColor: 'rgba(90, 108, 132, 0.25)',
    borderColor: 'rgba(122, 140, 164, 0.45)',
  },
  miningGaugePct: {
    width: 36,
    textAlign: 'right',
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: '#FFE6A1',
  },
  miningSummary: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: TACTICAL_HUB.miningSummaryInk,
  },
  miningSummaryMuted: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: COLORS.ink_light,
  },
  miningActionsWrap: {
    rowGap: 8,
  },
  miningControlRow: {
    flexDirection: 'row',
    columnGap: SPACING.sm,
  },
  miningControlBtn: {
    borderWidth: 1,
    borderColor: TACTICAL_HUB.controlBtnBorder,
    borderRadius: 8,
    backgroundColor: TACTICAL_HUB.controlBtnBg,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  miningControlText: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: TACTICAL_HUB.chromeInk,
    fontWeight: FONTS.weight.bold,
  },
  stanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.md,
    columnGap: SPACING.sm,
    marginBottom: 4,
  },
  stanceRowHidden: {
    opacity: 0,
  },
  stanceBtn: {
    width: '30.5%',
    backgroundColor: TACTICAL_HUB.tileBg,
    borderWidth: 1,
    borderColor: TACTICAL_HUB.tileBorder,
    borderRadius: 6,
    paddingVertical: SPACING.md,
    alignItems: 'center',
  },
  stanceLabel: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: TACTICAL_HUB.tileLabelInk,
  },
  menuBtn: {
    position: 'relative',
    width: '18%',
    backgroundColor: TACTICAL_HUB.tileBg,
    borderWidth: 1,
    borderColor: TACTICAL_HUB.tileBorder,
    borderRadius: 6,
    paddingVertical: SPACING.sm,
    alignItems: 'center',
  },
  menuBadgeDot: {
    position: 'absolute',
    top: -5.6,
    right: -5.6,
    width: 11.2,
    height: 11.2,
    borderRadius: 5.6,
    backgroundColor: '#8A1538',
  },
  menuBtnPrimary: {
    backgroundColor: TACTICAL_HUB.tilePrimaryBg,
    borderColor: TACTICAL_HUB.tilePrimaryBorder,
  },
  menuBtnDisabled: {
    opacity: 0.35,
  },
  menuLabel: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.sm,
    fontWeight: FONTS.weight.bold,
    color: TACTICAL_HUB.tileLabelInk,
  },
  menuLabelPrimary: { color: TACTICAL_HUB.tilePrimaryInk },
  menuLabelDisabled: { color: TACTICAL_HUB.tileDisabledInk },
  bottomFeatureReserve: {
    width: '100%',
    marginHorizontal: SPACING.md,
    marginBottom: SPACING.md,
    alignSelf: 'center',
    maxWidth: 430,
    backgroundColor: 'transparent',
  },
});

export const planetHubBgStyles = StyleSheet.create({
  root: {
    flex: 1,
    alignItems: 'center',
  },
  nebulaBackdropLayer: {
    position: 'absolute',
    opacity: 0.94,
  },
  /** 배지는 상단 고정, 행성은 아래 `planetOrbitSlot`에서만 수직 조정 */
  planetBgStack: {
    flex: 1,
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
  },
  systemBadge: {
    width: '100%',
    maxWidth: 340,
    alignSelf: 'center',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    zIndex: 20,
    ...(Platform.OS === 'android' ? { elevation: 20 } : {}),
    /** 행성 궤도와 붙이기 — 배지 자체 Y는 스택 상단에서 동일 */
    marginBottom: SPACING.xs,
  },
  /** 자본궤도 전투 중 — 성계 배지 전체를 살짝 투명하게(텍스트는 별도 회색 톤) */
  planetHubCapitalCombatBadgeDim: {
    opacity: 0.9,
  },
  /** 자본궤도 전투 중 — 궤도 연출(전투 SVG 제외) 투명도 */
  planetHubCapitalCombatOrbitDim: {
    opacity: PLANET_HUB_CAPITAL_COMBAT_DIM_OPACITY,
  },
  planetOrbitSlot: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  zoneBadge: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    borderWidth: 1,
    borderRadius: 2,
    paddingHorizontal: SPACING.xs,
    paddingVertical: 1,
  },
  zoneBadgeSafe: {
    color: COLORS.safe_zone,
    borderColor: COLORS.safe_zone,
    fontWeight: FONTS.weight.bold,
  },
  systemNameSlot: {
    alignSelf: 'stretch',
    justifyContent: 'center',
    marginTop: SPACING.sm,
  },
  systemName: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.md,
    color: COLORS.ink_mid,
    textAlign: 'center',
    alignSelf: 'stretch',
    textShadowColor: 'rgba(6,10,20,0.9)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  /** 클랜 마크/소유 — `systemBadge` 내 고정 슬롯(`planetMainStageLayout` 높이와 동기) */
  clanPlateInBadge: {
    alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  territorySubtitle: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: COLORS.ink_mid,
    opacity: 0.92,
    textAlign: 'center',
    alignSelf: 'stretch',
    marginTop: 2,
    textShadowColor: 'rgba(6,10,20,0.85)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  planetColumn: {
    alignItems: 'center',
    maxWidth: 430,
    alignSelf: 'center',
    width: '100%',
  },
  /** 클랜 소유(솔라 스테이션과 동일 플로우) — 별도 translate/마진 보정 없음 */
  safeAiClanPlate: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    maxWidth: 320,
    marginBottom: SPACING.sm,
    paddingVertical: SPACING.sm,
    paddingHorizontal: SPACING.md,
    borderRadius: 8,
    borderWidth: 0,
    backgroundColor: 'transparent',
  },
  safeAiClanPlateMark: {
    marginRight: SPACING.sm,
  },
  safeAiClanPlateTextCol: {
    flexShrink: 1,
    minWidth: 0,
    maxWidth: 260,
  },
  safeAiClanPlateClan: {
    fontFamily: FONTS.mono,
    fontSize: FONTS.size.xs,
    color: COLORS.ink_light,
    fontWeight: '400',
    textAlign: 'center',
  },
  orbitScene: {
    width: ORBIT_SCENE_SIZE,
    height: ORBIT_SCENE_SIZE,
    alignSelf: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  orbitLayerPlanet: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  planetTapHitbox: {
    position: 'absolute',
    width: 164,
    height: 164,
    borderRadius: 82,
    backgroundColor: 'transparent',
  },
  orbitLayerWorldObjects: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  orbitLayerShips: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  orbitLayerArcNpcTraffic: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 3,
  },
  orbitLayerPlayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 4,
  },
  orbitTestLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 5,
    transform: [
      { scaleX: PLANET_MAIN_COMBAT_LAYER_WIDTH_SCALE_X },
      { scaleY: PLANET_MAIN_COMBAT_LAYER_HEIGHT_SCALE_Y },
    ],
    ...(Platform.OS === 'android' ? { elevation: 8 } : {}),
  },
  orbitMarkWrap: {
    position: 'absolute',
    width: 14,
    height: 14,
    left: 0,
    top: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  /** 플레이어 함선 닉네임 — worldObjectCaption(96px) 클리핑 방지 */
  orbitPlayerMarkWrap: {
    overflow: 'visible',
  },
  worldObjectMarkWrap: {
    width: WORLD_OBJECT_ANCHOR_PX * 2,
    height: WORLD_OBJECT_ANCHOR_PX * 2,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'visible',
  },
  orbitMarkLabelCol: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    maxWidth: 220,
  },
  worldObjectLabelCol: {
    width: WORLD_OBJECT_ANCHOR_PX * 2,
    minHeight: WORLD_OBJECT_ANCHOR_PX * 2,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'visible',
  },
  worldObjectMiningOverlay: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: WORLD_OBJECT_ANCHOR_PX * 2,
    height: WORLD_OBJECT_ANCHOR_PX * 2,
    overflow: 'visible',
  },
  worldObjectMiningGuideSvg: {
    position: 'absolute',
    left: WORLD_OBJECT_ANCHOR_PX,
    top: WORLD_OBJECT_ANCHOR_PX - MINING_GUIDE_LINE_RUN_PX,
  },
  worldObjectCaptionOverlay: {
    position: 'absolute',
    left: -(96 - WORLD_OBJECT_ANCHOR_PX * 2) / 2,
    top: WORLD_OBJECT_ANCHOR_PX * 2 + 4,
  },
  orbitMarkGray: {
    fontFamily: FONTS.mono,
    fontSize: 9,
    color: '#8B95A8',
    lineHeight: 11,
    textAlign: 'center',
  },
  worldObjectGlyph: {
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: 11,
    color: '#A7E0FF',
    textAlign: 'center',
  },
  worldObjectAsteroidDot: {
    width: 15,
    height: 15,
    borderRadius: 8,
    backgroundColor: '#F5D86B',
    borderWidth: 2,
    borderColor: 'rgba(255, 245, 205, 0.95)',
  },
  worldObjectAsteroidDotInactive: {
    backgroundColor: '#7C8798',
    borderColor: 'rgba(180, 190, 206, 0.75)',
  },
  worldObjectWreckMark: {
    width: WORLD_OBJECT_WRECK_MARK_PX,
    height: WORLD_OBJECT_WRECK_MARK_PX,
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: WORLD_OBJECT_WRECK_STROKE_COLOR,
    borderRadius: 1,
  },
  worldObjectDefenseSatelliteWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    width: WORLD_OBJECT_ANCHOR_PX * 2,
    height: WORLD_OBJECT_ANCHOR_PX * 2,
  },
  worldObjectDefenseZoneRing: {
    position: 'absolute',
    borderWidth: 1,
    borderColor: WORLD_OBJECT_DEFENSE_ZONE_STROKE,
    backgroundColor: 'transparent',
  },
  worldObjectDefenseSatelliteMark: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderLeftWidth: WORLD_OBJECT_DEFENSE_SATELLITE_MARK_PX / 2,
    borderRightWidth: WORLD_OBJECT_DEFENSE_SATELLITE_MARK_PX / 2,
    borderBottomWidth: WORLD_OBJECT_DEFENSE_SATELLITE_MARK_PX,
    borderTopWidth: 0,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: WORLD_OBJECT_DEFENSE_SATELLITE_COLOR,
  },
  worldObjectMiningGuideWrap: {
    position: 'absolute',
    left:
      WORLD_OBJECT_ANCHOR_PX +
      MINING_GUIDE_LINE_RUN_PX +
      MINING_GUIDE_LABEL_PAST_TIP_PX,
    top:
      WORLD_OBJECT_ANCHOR_PX -
      MINING_GUIDE_LINE_RUN_PX -
      MINING_GUIDE_LABEL_PAST_TIP_PX,
    alignItems: 'flex-start',
    width: 120,
  },
  worldObjectMiningLabel: {
    marginLeft: 0,
    marginTop: 0,
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: 11,
    color: '#FFE4A3',
    textShadowColor: 'rgba(6,10,18,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  worldObjectMiningLabelActive: {
    color: '#71E391',
  },
  worldObjectMiningGaugeRow: {
    marginLeft: 0,
    marginTop: 1,
    flexDirection: 'row',
    columnGap: 1,
  },
  worldObjectMiningGaugeSeg: {
    width: 5,
    height: 4,
    borderRadius: 1,
    borderWidth: 1,
  },
  worldObjectMiningGaugeSegOn: {
    backgroundColor: '#F5D86B',
    borderColor: '#FFE8A6',
  },
  worldObjectMiningGaugeSegOff: {
    backgroundColor: 'rgba(90,108,132,0.25)',
    borderColor: 'rgba(122,140,164,0.45)',
  },
  worldObjectMiningGaugeSegPaused: {
    opacity: 0.45,
  },
  worldObjectCaption: {
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: 12,
    width: 96,
    textAlign: 'center',
    color: 'rgba(188,214,238,0.9)',
    textShadowColor: 'rgba(6,10,18,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
  orbitShipCaption: {
    fontFamily: FONTS.mono,
    fontSize: 6,
    lineHeight: 8,
    color: 'rgba(200,208,220,0.92)',
    textAlign: 'center',
    marginTop: 1,
    maxWidth: 70,
    textShadowColor: 'rgba(6,10,20,0.75)',
    textShadowOffset: { width: 0, height: 0.5 },
    textShadowRadius: 1.5,
  },
  orbitMarkPlayerBlue: {
    fontFamily: FONTS.mono,
    fontSize: 10,
    color: '#6CB6FF',
    lineHeight: 12,
    textAlign: 'center',
    textShadowColor: 'rgba(8,16,32,0.75)',
    textShadowOffset: { width: 0, height: 0.5 },
    textShadowRadius: 1.5,
  },
  orbitShipCaptionPlayerBlue: {
    fontFamily: FONTS.mono,
    fontSize: 9,
    lineHeight: 12,
    width: 96,
    color: '#9ED0FF',
    textAlign: 'center',
    marginBottom: 1,
    textShadowColor: 'rgba(6,10,18,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },
});
